services:
  backend:
    build: ./
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    env_file:
      - ./global.env
    environment:
      - PGHOST=db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 5

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d checkpoint2 -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkpoint2
    ports:
      - 5433:5432
    volumes:
      - checkpoint2Data:/var/lib/postgresql/data

volumes:
  checkpoint2Data:
